# Generated by Django 4.1.3 on 2022-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('no_of_questions', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Duration of the quiz')),
                ('passing', models.IntegerField(help_text='Required score to pass')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
            ],
        ),
    ]
